# Solving linear equations

# I. $LU$ factorization of a square matrix

Let us consider a decomposition of a square $n \times n$ matrix A as follows:
$$A = L \cdot U, \; \mbox{where} \; A = \begin{pmatrix} 
                                            a_{11} & a_{12} & a_{13} & \ldots & a_{1n} \\
                                            a_{21} & a_{22} & a_{23} & \ldots & a_{2n} \\
                                            a_{31} & a_{32} & a_{33} & \ldots & a_{3n} \\
                                            \vdots & \vdots & \vdots & \ddots & \vdots \\
                                            a_{n1} & a_{n2} & a_{n3} & \ldots & a_{nn} \\
                                        \end{pmatrix}
                               , \; L = \begin{pmatrix} 
                                            1 & 0 & 0 & \ldots & 0 \\
                                            * & 1 & 0 & \ldots & 0 \\
                                            * & * & 1 & \ldots & 0 \\
                                            \vdots & \vdots & \vdots & \ddots & \vdots \\
                                            * & * & * & \ldots & 1 \\
                                        \end{pmatrix}
                               , \; U = \begin{pmatrix} 
                                            a_{11} & * & * & \ldots & * \\
                                            0 & a_{22} & * & \ldots & * \\
                                            0 & 0 & a_{33} & \ldots & * \\
                                            \vdots & \vdots & \vdots & \ddots & \vdots \\
                                            0 & 0 & 0 & \ldots & a_{nn} \\
                                        \end{pmatrix} .$$

Let's start with Gaussian elimination. When we are working with the first column, we combine the first row and the second row multiplied by coefficient $$\gamma_{21} = \cfrac{a_{21}}{a{11}};$$ then the first row and the third row multiplied by coefficient $$\gamma_{31} = \cfrac{a_{31}}{a{11}},$$ and so on.

Hereby, to eliminate all elements below $a_{11}$ we need to multiply matrix A by matrix $$\Lambda_1 = \begin{pmatrix} 
                                                        1 & 0 & 0 & \ldots & 0 \\
                                                        -\gamma_{21} & 1 & 0 & \ldots & 0 \\
                                                        -\gamma_{31} & 0 & 1 & \ldots & 0 \\
                                                        \vdots & \vdots & \vdots & \ddots & \vdots \\
                                                        -\gamma_{n1} & 0 & 0 & \ldots & 1 \\
                                                    \end{pmatrix}$$
(prove it by trying to act with $\Lambda_1$ on the first column of matrix A).

Likewise, we can construct matrix $\Lambda_2$ as $$\Lambda_2 = \begin{pmatrix} 
                                                                1 & 0 & 0 & \ldots & 0 \\
                                                                0 & 1 & 0 & \ldots & 0 \\
                                                                0 & -\gamma_{32} & 1 & \ldots & 0 \\
                                                                \vdots & \vdots & \vdots & \ddots & \vdots \\
                                                                0 & -\gamma_{n2} & 0 & \ldots & 1 \\
                                                            \end{pmatrix}.$$

Finally, we will get the upper triangular matrix $$U = \Lambda_n \cdot \Lambda_{n-1} \cdot \ldots \cdot \Lambda_2 \cdot \Lambda_1 A. $$
Hence the lower triangular matrix $L = \Lambda_1^{-1} \cdot \Lambda_2^{-1} \cdot \ldots \cdot \Lambda_{n-1}^{-1} \cdot \Lambda_n^{-1}.$

One can show that, for example, $$\Lambda_1^{-1} = \begin{pmatrix} 
                                                        1 & 0 & 0 & \ldots & 0 \\
                                                        \gamma_{21} & 1 & 0 & \ldots & 0 \\
                                                        \gamma_{31} & 0 & 1 & \ldots & 0 \\
                                                        \vdots & \vdots & \vdots & \ddots & \vdots \\
                                                        \gamma_{n1} & 0 & 0 & \ldots & 1 \\
                                                    \end{pmatrix}$$

Note that we're using the `numpy` arrays to represent matrices [do **not** use `np.matrix`].

In [3]:
import numpy as np

def diy_lu_ext(a):
    """
    Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    #Initializing the factors
    u = a.copy()
    L = np.eye(N)
    
    for j in range(N-1):
        lam = np.eye(N)
        
        #Creating the vector of gammas
        gamma = np.zeros(N-j-1)
        for i in range(N-j-1):
            gamma[i] = u[j+1+i, j]/u[j, j]
        
        #Creating matrix \Lambda_i
        for i in range(N-j-1):
            lam[j+1+i, j] = -gamma[i]
        
        #Acting with \Lambda_i on A to get U
        u_new = np.zeros((N, N))
        for ind_i in range(N):
            for ind_j in range(N):
                for ind_k in range(N):
                    u_new[ind_i, ind_j] += lam[ind_i, ind_k] * u[ind_k, ind_j]
        u = u_new.copy()
        
        #Creating matrix \Lambda_i^{-1}
        for i in range(N-j-1):
            lam[j+1+i, j] = gamma[i]
            
        #Multiplying L and \Lambda_i^{-1} o get new L
        L_new = np.zeros((N, N))
        for ind_i in range(N):
            for ind_j in range(N):
                for ind_k in range(N):
                    L_new[ind_i, ind_j] += L[ind_i, ind_k] * lam[ind_k, ind_j]
        L = L_new.copy()
        
    return L, u

In [11]:
# Now, generate a full rank matrix and test the naive implementation

import numpy as np

N = 6
a = np.zeros((N, N), dtype=float)
for i in range(N):
    for j in range(N):
        a[i, j] = 3. / (0.6*i*j + 1)

np.linalg.matrix_rank(a) 

6

In [5]:
L, u = diy_lu_ext(a)
print(L@u - a)

[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.22044605e-16
  -1.11022302e-16 -1.66533454e-16]
 [ 0.00000000e+00  0.00000000e+00  2.22044605e-16 -5.55111512e-17
  -1.66533454e-16 -1.66533454e-16]
 [ 0.00000000e+00  0.00000000e+00 -1.11022302e-16 -1.66533454e-16
   1.66533454e-16  5.55111512e-17]
 [ 0.00000000e+00  0.00000000e+00 -1.66533454e-16 -1.66533454e-16
   5.55111512e-17  0.00000000e+00]]


LU can be programmed in a more simple way by using the perks of `numpy`.

In [2]:
import numpy as np

def diy_lu(a):
    """
    Construct the LU decomposition of the input matrix.
    
    Naive LU decomposition: work column by column, accumulate elementary triangular matrices.
    No pivoting.
    """
    N = a.shape[0]
    
    u = a.copy()
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        
        #Creating the vector of gammas
        gamma = u[j+1:, j] / u[j, j]
        
        #Creating matrix \Lambda_i
        lam[j+1:, j] = -gamma
        
        #Acting with \Lambda_i on A to get U
        u = lam @ u
        
        #Creating matrix \Lambda_i^{-1}
        lam[j+1:, j] = gamma
            
        #Multiplying L and \Lambda_i^{-1} o get new L
        L = L @ lam
    return L, u

In [7]:
# Tweak the printing of floating-point numbers, for clarity
np.set_printoptions(precision=3)

In [8]:
L, u = diy_lu(a)

print(L, "\n")
print(u, "\n")

# Quick sanity check: L times U must equal the original matrix, up to floating-point errors.
print(L@u - a)

[[1.    0.    0.    0.    0.    0.   ]
 [1.    1.    0.    0.    0.    0.   ]
 [1.    1.455 1.    0.    0.    0.   ]
 [1.    1.714 1.742 1.    0.    0.   ]
 [1.    1.882 2.276 2.039 1.    0.   ]
 [1.    2.    2.671 2.944 2.354 1.   ]] 

[[ 3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00  3.000e+00]
 [ 0.000e+00 -1.125e+00 -1.636e+00 -1.929e+00 -2.118e+00 -2.250e+00]
 [ 0.000e+00  0.000e+00  2.625e-01  4.574e-01  5.975e-01  7.013e-01]
 [ 0.000e+00  2.220e-16  0.000e+00 -2.197e-02 -4.480e-02 -6.469e-02]
 [ 0.000e+00 -4.528e-16  0.000e+00  6.939e-18  8.080e-04  1.902e-03]
 [ 0.000e+00  4.123e-16  0.000e+00 -1.634e-17  0.000e+00 -1.585e-05]] 

[[ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00  0.000e+00]
 [ 0.000e+00  0.000e+00  0.000e+00  2.220e-16 -1.110e-16 -1.665e-16]
 [ 0.000e+00  0.000e+00  2.220e-16 -5.551e-17 -1.665e-16 -1.665e-16]
 [ 0.000e+00  0.000e+00 -1.110e-16 -1.665e-16  1.665e-16  5.551e-17]
 

# II. The need for pivoting

Let's tweak the matrix a little bit, we only change a single element:

In [12]:
a1 = a.copy()
a1[1, 1] = 3

Resulting matrix still has full rank, but the naive LU routine breaks down.

In [10]:
np.linalg.matrix_rank(a1)

6

In [11]:
l, u = diy_lu(a1)

print(l, u)

[[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]] [[nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]
 [nan nan nan nan nan nan]]


C:\an\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: divide by zero encountered in true_divide
C:\an\lib\site-packages\ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in true_divide


### Test II.1

For a naive LU decomposition to work, all leading minors of a matrix should be non-zero. Check if this requirement is satisfied for the two matrices `a` and `a1`.

In [8]:
def minor(a):
    
    N = a.shape[0]
    x = 0
    for k in range(N+1):
        if np.linalg.det(a[:k+1,:k+1]) != 0:
            x +=1
    if x <= N:
        return print('not all leading minors of a matrix are non-zero')
    else:
        return print('all leading minors of a matrix are non-zero')

In [15]:
minor(a1)

not all leading minors of a matrix are non-zero


In [16]:
minor(a)

all leading minors of a matrix are non-zero


Test II.2

Modify the `diy_lu` routine to implement column pivoting. Keep track of pivots, you can either construct a permutation matrix, or a swap array (your choice).

Implement a function to reconstruct the original matrix from a decompositon. Test your routines on the matrices `a` and `a1`.

In [316]:
import numpy as np

def diy_lu_piv(a):
    
    N = a.shape[0]
    u = a.copy() 
    P = np.eye(N)
    L = np.eye(N)
    for j in range(N-1):
        lam = np.eye(N)
        
        #Поиск опорного элемента
        max_index = np.argmax(abs(u[j:N,j]))+j
        piv = np.arange(0,N)
        piv[[j,max_index]] = piv[[max_index,j]]
        u = u[piv]
        P = P[piv]
        
        #Creating the vector of gammas
        gamma = u[j+1:, j] / u[j, j]
        
        #Creating matrix \Lambda_i
        lam[j+1:, j] = -gamma
        
        #Acting with \Lambda_i on A to get U
        u = lam @ u
        
        #Creating matrix \Lambda_i^{-1}
        lam[j+1:, j] = gamma
            
        #Multiplying L and \Lambda_i^{-1} o get new L
        L = L @ lam
        if j>=1:
            L[:,0:j] = L[:,0:j][piv]
        
    return L, u, P

In [317]:
diy_lu_piv(a)

(array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 1.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.5       , 1.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.72727273, 0.70588235, 1.        , 0.        ,
         0.        ],
        [1.        , 0.85714286, 0.40993789, 0.83482143, 1.        ,
         0.        ],
        [1.        , 0.94117647, 0.17849899, 0.4255677 , 0.78870221,
         1.        ]]),
 array([[ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
          3.00000000e+00,  3.00000000e+00,  3.00000000e+00],
        [ 0.00000000e+00, -2.25000000e+00, -2.57142857e+00,
         -2.70000000e+00, -2.76923077e+00, -2.81250000e+00],
        [ 0.00000000e+00,  0.00000000e+00, -3.50649351e-01,
         -5.78571429e-01, -7.33031674e-01, -8.43750000e-01],
        [ 0.00000000e+00,  0.00000000e+00,  2.77555756e-17,
          2.42136380e-02,  4.

In [318]:
diy_lu_piv(a1)

(array([[1.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 1.        , 0.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.        , 1.        , 0.        , 0.        ,
         0.        ],
        [1.        , 0.72727273, 0.1512605 , 1.        , 0.        ,
         0.        ],
        [1.        , 0.85714286, 0.08784383, 0.51421669, 1.        ,
         0.        ],
        [1.        , 0.94117647, 0.03824978, 0.2076544 , 0.64143198,
         1.        ]]),
 array([[ 3.00000000e+00,  3.00000000e+00,  3.00000000e+00,
          3.00000000e+00,  3.00000000e+00,  3.00000000e+00],
        [ 0.00000000e+00, -2.25000000e+00, -2.57142857e+00,
         -2.70000000e+00, -2.76923077e+00, -2.81250000e+00],
        [ 0.00000000e+00,  0.00000000e+00, -1.63636364e+00,
         -1.92857143e+00, -2.11764706e+00, -2.25000000e+00],
        [ 0.00000000e+00,  0.00000000e+00,  2.77555756e-17,
         -9.24730366e-02, -1.

Sum all elements in matrix `L1` and `u1` separately (for Google Form).

In [337]:
L1, u1, P1 = diy_lu_piv(a1)
def sumColumn(matrix):
    return np.sum(matrix, axis=1)
sum(sumColumn(L1))

15.166249240140566

In [338]:
sum(sumColumn(u1))

-3.4566590083280793